# import sys
# from PyQt5.QtWidgets import QWidget, QToolTip, QPushButton, QApplication, QMainWindow, QLabel
# from PyQt5.QtGui import QFont
#
#
# class WindowTest(QMainWindow):
#     """
#     Window class
#     """
#     def __init__(self):
#         super(WindowTest, self).__init__()
#
#         self.initUI()
#
#     def initUI(self):
#         """
#         UI initializer
#         :return:
#         :rtype:
#         """
#         label = QLabel(self)
#
#         label.setText("hi")
#         label.move(50, 50)
#
#         btn = QPushButton("image of plus", self)
#         btn.resize(btn.sizeHint())
#         btn.move(100, 100)
#
#         self.setGeometry(200, 200, 300, 300)
#         self.setWindowTitle("Create new doc")
#         self.resize(1000, 500)
#         self.show()
#
#         def onclick():
#             """
#             button clickes
#             :return:
#             :rtype:
#             """
#             self.label.setText("Btn clicked")
#
#
# def onclick():
#     """
#     button clickes
#     :return:
#     :rtype:
#     """
#     print("clicked")
#
#
# def main():
#     """
#
#     :return:
#     :rtype:
#     """
#     app = QApplication(sys.argv)
#     win = WindowTest()
#     win.show()
#     exit(app.exec_())
#
#
# if __name__ == '__main__':
#     main()


# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'upload.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys

from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5.QtCore import *

# WHITE=QtGui.QColor(255,255,255)

class Hypnos:
    def __init__(self):
        # super().__init__()
        self.app = QApplication(sys.argv)
        self.window = QMainWindow()

        self.window.stylesheet = """
            QPushButton#uploadButton{
                background-color: #173042;
                color: #fff;
                border-radius: 10px;
                font-size: 25px;
                font-family: 'Roboto';
                font-weight: 3000;
            }
            QPushButton#plusButton{
                background-color: #31BE8B;
                background-image: url(images/icon (1).png);
                border-radius: 50px;
                background-repeat: repeat;
                background-attachment: fixed;
                background-position: center;
            }"""

        self.UiComponents()

        # setting the window title
        self.window.setWindowTitle("Hypnos")
        # sizing the mainWindow
        self.window.setGeometry(1000, 1000, 1000, 1000)
        self.window.show()
        self.app.setStyleSheet(self.window.stylesheet)
        sys.exit(self.app.exec_())

        # method for widgets
    def UiComponents(self):

        uploadButton = QPushButton(self.window)
        uploadButton.setText("Upload audio file")
        uploadButton.setGeometry(200, 150, 100, 100)
        uploadButton.resize(400, 100)
        uploadButton.clicked.connect(self.openUserFiles)
        uploadButton.setObjectName("uploadButton")

        plusButton = QPushButton(self.window)
        plusButton.setGeometry(50, 150, 100, 100)
        plusButton.setObjectName("plusButton")



    def openUserFiles(self):
        #opening the file dialog for selecting the file
        fname = QFileDialog.getOpenFileName(self, 'Open File', 'c:\\', "Video Files(*.mp4)")
        print(fname[0]) #fname[0] is the absolute file path
        #connection to the backend happens here


if __name__ == "__main__":
    main = Hypnos()
