# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'transcript.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

WHITE=QtGui.QColor(255,255,255)

class Ui_MainWindow(QtWidgets.QMainWindow,object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Alef")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(90, 10, 591, 361))
        self.textEdit.setObjectName("textEdit")
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(260, 380, 221, 61))
        self.saveButton.clicked.connect(self.save)
        font = QtGui.QFont()
        font.setFamily("Alef")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.saveButton.setFont(font)
        self.saveButton.setAutoFillBackground(True)
        self.saveButton.setStyleSheet("background-color=blurgb(85, 170, 255)e;\n"
"border-style=outset;\n"
"border-width=2px;\n"
"border-radius=10px;\n"
"border-color=blue;")
        self.saveButton.setObjectName("saveButton")

        self.summarizeButton = QtWidgets.QPushButton(self.centralwidget)
        self.summarizeButton.setGeometry(QtCore.QRect(260, 460, 221, 61))
        self.summarizeButton.setObjectName("summarizeButton")
        self.summarizeButton.setFont(font)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 37))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Transcript"))
        self.saveButton.setText(_translate("MainWindow", "Save"))
        self.summarizeButton.setText(_translate("MainWindow", "Summarize"))

    def save(self):
        fname=QtWidgets.QFileDialog.getSaveFileName(self,'Save File')
        data=self.textEdit.toPlainText()
        if fname[0]:
            file=open(fname[0],'w')
            file.write(data)
            file.close()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setStyle('Fusion')
    dark_palette = QtGui.QPalette()

    dark_palette.setColor(QtGui.QPalette.Window, QtGui.QColor(53, 53, 53))
    dark_palette.setColor(QtGui.QPalette.WindowText, WHITE)
    dark_palette.setColor(QtGui.QPalette.Base, QtGui.QColor(25, 25, 25))
    dark_palette.setColor(QtGui.QPalette.AlternateBase, QtGui.QColor(53, 53, 53))
    dark_palette.setColor(QtGui.QPalette.ToolTipBase,WHITE)
    dark_palette.setColor(QtGui.QPalette.ToolTipText,WHITE)
    dark_palette.setColor(QtGui.QPalette.Text, WHITE)
    dark_palette.setColor(QtGui.QPalette.Button, QtCore.Qt.blue)
    dark_palette.setColor(QtGui.QPalette.ButtonText,WHITE)
    dark_palette.setColor(QtGui.QPalette.BrightText,QtGui.QColor(255,0,0))
    dark_palette.setColor(QtGui.QPalette.Link,QtGui.QColor(42, 130, 218))
    dark_palette.setColor(QtGui.QPalette.Highlight, QtGui.QColor(42, 130, 218))
    dark_palette.setColor(QtGui.QPalette.HighlightedText, QtGui.QColor(0,0,0))

    app.setPalette(dark_palette)

    app.setStyleSheet("QToolTip { color: #ffffff; background-color: #2a82da; border: 1px solid white; }")
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
