# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'upload.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore,QtGui,QtWidgets
import sys

class Ui_Hypnos(QtWidgets.QMainWindow):
    def __init__(self):

        super().__init__()
        self.setWindowTitle("Hypnos")
        self.resize(800,600)

        self.upload_button()

        self.show()



    def upload_button(self):

        self.uploadButton = QtWidgets.QPushButton("Upload files here",self)
        self.uploadButton.setGeometry(QtCore.QRect(200, 210, 371, 111))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.uploadButton.setFont(font)
        self.uploadButton.setObjectName("uploadButton")
        self.uploadButton.setStyleSheet("background-color=blurgb(85, 170, 255)")
        self.uploadButton.setStyleSheet("border-style=outset")
        self.uploadButton.setStyleSheet("border-width=2px")
        self.uploadButton.setStyleSheet("border-radius=10px")
        self.uploadButton.clicked.connect(self.open)
    def open(self):
        fname=QtWidgets.QFileDialog.getOpenFileName(self,'Open File', 'c:\\',"Video Files(*.mp4)")
        print(fname[0])
        #call to the backend happens here
app=QtWidgets.QApplication(sys.argv)
app.setStyle('Fusion')
window=Ui_Hypnos()
sys.exit(app.exec_())
