# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'upload.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Hypnos(QtWidgets.QMainWindow,object):
    def setupUi(self, Hypnos):
        Hypnos.setObjectName("Hypnos")
        Hypnos.resize(800, 600)
        Hypnos.setWindowTitle("Hypnos")
        self.centralwidget = QtWidgets.QWidget(Hypnos)
        self.centralwidget.setObjectName("centralwidget")

        self.uploadButton = QtWidgets.QPushButton(self.centralwidget)
        self.uploadButton.setGeometry(QtCore.QRect(200, 210, 371, 111))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.uploadButton.setFont(font)
        self.uploadButton.setAutoFillBackground(True)
        self.uploadButton.setObjectName("uploadButton")
        self.uploadButton.setStyleSheet("background-color=blurgb(85, 170, 255)")
        self.uploadButton.setStyleSheet("border-style=outset")
        self.uploadButton.setStyleSheet("border-width=2px")
        self.uploadButton.setStyleSheet("border-radius=10px")
        self.uploadButton.clicked.connect(self.open)

        Hypnos.setCentralWidget(self.centralwidget)


        self.menubar = QtWidgets.QMenuBar(Hypnos)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        Hypnos.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Hypnos)
        self.statusbar.setObjectName("statusbar")
        Hypnos.setStatusBar(self.statusbar)

        self.retranslateUi(Hypnos)
        QtCore.QMetaObject.connectSlotsByName(Hypnos)

    def retranslateUi(self, Hypnos):
        _translate = QtCore.QCoreApplication.translate
        Hypnos.setWindowTitle(_translate("Hypnos", "MainWindow"))
        self.uploadButton.setWhatsThis(_translate("Hypnos", "Upload files "))
        self.uploadButton.setText(_translate("Hypnos", "Upload New Files"))

    def open(self):
        fname=QtWidgets.QFileDialog.getOpenFileName(self,'Open File', 'c:\\',"Video Files(*.mp4)")
        print(fname[0])


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setStyle('Windows')
    Hypnos = QtWidgets.QMainWindow()
    ui = Ui_Hypnos()
    ui.setupUi(Hypnos)
    Hypnos.show()
    sys.exit(app.exec_())
